# Generated by Django 4.2.5 on 2023-09-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NickName', models.CharField(max_length=60)),
                ('UserName', models.CharField(max_length=60)),
                ('UserDate', models.DateField()),
                ('UserAddress', models.CharField(max_length=60)),
                ('UserPass', models.CharField(max_length=20)),
                ('UserEmail', models.EmailField(max_length=254)),
                ('UserTnum', models.CharField(max_length=20)),
            ],
        ),
    ]
