# Generated by Django 4.2.5 on 2023-09-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=60)),
                ('Modelo', models.CharField(max_length=60)),
                ('año', models.DateField()),
                ('color', models.CharField(max_length=20)),
                ('precio', models.FloatField(max_length=10)),
                ('descrip', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('subtipo', models.CharField(max_length=30)),
                ('precio', models.FloatField(max_length=10)),
                ('descrip', models.CharField(max_length=500)),
            ],
        ),
    ]
