# Generated by Django 4.2.5 on 2023-09-25 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0002_articulo_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articulo',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='descrip',
            new_name='Descrip',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='precio',
            new_name='Precio',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='subtipo',
            new_name='Subtipo',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='tipo',
            new_name='Tipo',
        ),
    ]
