# Generated by Django 4.2.5 on 2023-09-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0003_delete_articulo_rename_descrip_service_descrip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marca', models.CharField(max_length=60)),
                ('Modelo', models.CharField(max_length=60)),
                ('Year', models.CharField(max_length=4)),
                ('Color', models.CharField(max_length=20)),
                ('Precio', models.FloatField(max_length=10)),
                ('Descrip', models.CharField(max_length=500)),
            ],
        ),
    ]
